### PR TITLE
fixed typo in NAME description

### PR DESCRIPTION
**Pull request by kberov**

### CODE REVIEW

**Comment by kberov** [comment]
All tests failed in Travis CI because:
```
[checked] bin/tidyall
Wide character in print at /home/travis/perl5/perlbrew/perls/5.20-extras/lib/site_perl/5.20.0/File/Slurp/Tiny.pm line 55.
[checked] lib/Code/TidyAll.pm
/tmp/Code-TidyAll-Ytg4/TidyAll.pm around line 722: Non-ASCII character seen before =encoding in 'Красимир'. Assuming UTF-8
/home/travis/perl5/perlbrew/perls/5.20-extras/bin/dzil: omitting file `/tmp/Code-TidyAll-Ytg4/TidyAll.pm': bad Pod syntax
/tmp/Code-TidyAll-Ytg4/TidyAll.pm around line 722: Non-ASCII character seen before =encoding in 'Красимир'. Assuming UTF-8
/home/travis/perl5/perlbrew/perls/5.20-extras/bin/dzil: omitting file `/tmp/Code-TidyAll-Ytg4/TidyAll.pm': bad Pod syntax
```
I think this can serve as a bug report: build faile when author name contains non ASCII characters.

Regards,
Krasimir

**Comment by autarch** [comment]
The fix is to add `=encoding UTF-8` to the POD for Code::TidyAll. There's a Pod::Weaver plugin that inserts all contributor names from git into the final POD, and yours isn't in ASCII.

**Comment by kberov** [comment]
Is the ABSTRACT (NAME) missing on purpose in POD for Code::TidyAll?
There is an ABSTRACT but only as a comment several lines up.
https://github.com/autarch-code/perl-code-tidyall/blob/master/lib/Code/TidyAll.pm#L525
Should I add it as =head1 NAME
or leave it as it is?

**Comment by kberov** [comment]
Also it looks like metacpan.org refuses to show the POD for .pm files missing ABSTRACT in POD.
which sounds natural as there is no title for the documentation.

**Comment by autarch** [comment]
The abstract gets added by Dist::Zilla (via Pod::Weaver). I think I broke something in the dzil config in recent releases. I'll look into it.

**Comment by kberov** [comment]
Ok, thanks. Did not added NAME as I realized something takes care about it. Now tests should pass.

**Comment by autarch** [comment]
I just pushed some commits which fix this, and should cause your PR to pass in Travis too (I think).

**Comment by autarch** [comment]
So after all this I ended up fixing it by hand because I needed to make some other changes in the same module's POD. But thanks for finding the typo!

**Pull request closed without merging**
